import type { EvidenceDocument, LegalCase, Transaction, UploadItem } from './types';

export const demoCase: LegalCase = {
  id: 'case-001',
  title: 'Bennett v. Northline Logistics',
  caseType: 'Personal Injury',
  clientName: 'Maya Bennett',
  attorneyName: 'Elena Ruiz',
  createdAt: '2026-05-16',
};

export const documents: EvidenceDocument[] = [
  {
    id: 'doc-001',
    caseId: demoCase.id,
    originalFilename: 'metro_general_er_bill.pdf',
    documentType: 'Medical Bill',
    veryfiId: 'vf_93271',
    extractionStatus: 'complete',
    confidenceScore: 97,
    isFlagged: false,
    uploadedAt: '2026-05-16T09:12:00',
    thumbnailTone: '#cfe7f7',
  },
  {
    id: 'doc-002',
    caseId: demoCase.id,
    originalFilename: 'orthopedic_invoice_0412.pdf',
    documentType: 'Invoice',
    veryfiId: 'vf_93294',
    extractionStatus: 'review',
    confidenceScore: 83,
    isFlagged: true,
    flagReason: 'Possible digital alteration in total amount region',
    uploadedAt: '2026-05-16T09:16:00',
    thumbnailTone: '#f7dfcf',
  },
  {
    id: 'doc-003',
    caseId: demoCase.id,
    originalFilename: 'pharmacy_receipts_batch.jpg',
    documentType: 'Receipt',
    veryfiId: 'vf_93302',
    extractionStatus: 'complete',
    confidenceScore: 94,
    isFlagged: false,
    uploadedAt: '2026-05-16T09:21:00',
    thumbnailTone: '#d9ead7',
  },
  {
    id: 'doc-004',
    caseId: demoCase.id,
    originalFilename: 'rideshare_to_clinic.pdf',
    documentType: 'Receipt',
    veryfiId: 'vf_93318',
    extractionStatus: 'complete',
    confidenceScore: 91,
    isFlagged: true,
    flagReason: 'Duplicate candidate: same vendor, amount, and timestamp as doc-009',
    uploadedAt: '2026-05-16T09:25:00',
    thumbnailTone: '#e7ddfa',
  },
  {
    id: 'doc-005',
    caseId: demoCase.id,
    originalFilename: 'march_checking_statement.pdf',
    documentType: 'Bank Statement',
    veryfiId: 'vf_93344',
    extractionStatus: 'complete',
    confidenceScore: 96,
    isFlagged: false,
    uploadedAt: '2026-05-16T09:28:00',
    thumbnailTone: '#d9e0ea',
  },
];

export const transactions: Transaction[] = [
  {
    id: 'txn-001',
    documentId: 'doc-001',
    caseId: demoCase.id,
    date: '2026-03-04',
    vendorName: 'Metro General Hospital',
    category: 'Medical',
    amount: 4280,
    currency: 'USD',
    description: 'Emergency department evaluation, imaging, and trauma labs',
    lineItems: [
      { item: 'Emergency room facility', amount: 2100 },
      { item: 'CT scan cervical spine', amount: 1480 },
      { item: 'Lab panel', amount: 700 },
    ],
    isDuplicate: false,
    tamperingDetected: false,
  },
  {
    id: 'txn-002',
    documentId: 'doc-005',
    caseId: demoCase.id,
    date: '2026-03-07',
    vendorName: 'Northline Payroll',
    category: 'Lost Wages',
    amount: 1380,
    currency: 'USD',
    description: 'Missed weekly payroll deposit after injury leave began',
    lineItems: [{ item: 'Expected net payroll', amount: 1380 }],
    isDuplicate: false,
    tamperingDetected: false,
  },
  {
    id: 'txn-003',
    documentId: 'doc-003',
    caseId: demoCase.id,
    date: '2026-03-10',
    vendorName: 'Harris Pharmacy',
    category: 'Medical',
    amount: 187.42,
    currency: 'USD',
    description: 'Prescription pain management and brace supplies',
    lineItems: [
      { item: 'Cyclobenzaprine', amount: 42.18 },
      { item: 'Naproxen', amount: 18.75 },
      { item: 'Compression brace', amount: 126.49 },
    ],
    isDuplicate: false,
    tamperingDetected: false,
  },
  {
    id: 'txn-004',
    documentId: 'doc-004',
    caseId: demoCase.id,
    date: '2026-03-14',
    vendorName: 'RideWay',
    category: 'Transportation',
    amount: 46.88,
    currency: 'USD',
    description: 'Ride to orthopedic follow-up appointment',
    lineItems: [{ item: 'Medical transport ride', amount: 46.88 }],
    isDuplicate: true,
    tamperingDetected: false,
  },
  {
    id: 'txn-005',
    documentId: 'doc-002',
    caseId: demoCase.id,
    date: '2026-04-12',
    vendorName: 'Summit Orthopedics',
    category: 'Medical',
    amount: 3160,
    currency: 'USD',
    description: 'Specialist consultation, MRI review, physical therapy order',
    lineItems: [
      { item: 'Orthopedic consultation', amount: 650 },
      { item: 'MRI interpretation', amount: 910 },
      { item: 'Therapy plan', amount: 1600 },
    ],
    isDuplicate: false,
    tamperingDetected: true,
  },
  {
    id: 'txn-006',
    documentId: 'doc-005',
    caseId: demoCase.id,
    date: '2026-04-19',
    vendorName: 'Community Physical Therapy',
    category: 'Medical',
    amount: 840,
    currency: 'USD',
    description: 'Four post-accident physical therapy sessions',
    lineItems: [{ item: 'Physical therapy block', amount: 840 }],
    isDuplicate: false,
    tamperingDetected: false,
  },
];

export const simulatedUploads: UploadItem[] = [
  { id: 'up-001', filename: 'urgent_care_receipt.jpg', type: 'Receipt', progress: 100, status: 'complete', confidence: 95 },
  { id: 'up-002', filename: 'handwritten_parking_note.png', type: 'Handwritten Note', progress: 78, status: 'extracting' },
  { id: 'up-003', filename: 'april_statement.pdf', type: 'Bank Statement', progress: 41, status: 'extracting' },
  { id: 'up-004', filename: 'duplicate_ride_receipt.pdf', type: 'Receipt', progress: 100, status: 'review', confidence: 88 },
];

export const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
});
